<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Project;
use App\Models\Task;
use App\Models\Client;
use App\Models\Employee;
use App\Models\User;

class SeedScrumDemoData extends Seeder
{
    public function run()
    {
        // 1. Ensure a Client exists
        $client = Client::firstOrCreate(
            ['name' => 'Acme Corp'], 
            ['email' => 'contact@acme.com', 'code' => 'ACME', 'portal_access' => true]
        );

        // 2. Create a "Web Redesign" Project (Billable)
        $project = Project::firstOrCreate(
            ['code' => 'ACME-WEB'],
            [
            'client_id' => $client->id,
            'name' => 'Acme Web Redesign 2025',
            'status' => 'active',
            'visibility' => 'public',
            'billing_type' => 'hourly',
            'hourly_rate' => 120.00,
            'currency' => 'USD',
            'start_date' => now(),
            'deadline' => now()->addMonths(3)
        ]);

        // 3. Ensure Department exists
        $dept = \App\Models\Department::firstOrCreate(
            ['name' => 'Engineering'],
            [
                'tenant_id' => 1, 
                'code' => 'ENG',
                'head_id' => null
            ]
        );

        // 2. Ensure Developer Exists
        $dev = Employee::where('email', 'john@example.com')->first();
        if (!$dev) {
            // Create User first
            $tenant = \App\Models\Tenant::first();
            $user = \App\Models\User::firstOrCreate(
                ['email' => 'john@example.com'],
                [
                    'name' => 'John Doe',
                    'password' => \Illuminate\Support\Facades\Hash::make('password'),
                    'email_verified_at' => now(),
                    'tenant_id' => $tenant ? $tenant->id : 1,
                ]
            );

            // Link to Employee
            $dev = Employee::forceCreate([
                'uuid' => \Illuminate\Support\Str::uuid(),
                'tenant_id' => 1,
                'user_id' => $user->id,
                'first_name' => 'John',
                'last_name' => 'Doe',
                'email' => 'john@example.com',
                'employee_code' => 'EMP-007',
                'department_id' => $dept->id,
                'designation' => 'Senior Developer',
                'joining_date' => now(),
                'status' => 'active'
            ]);
            
            // Assign Role
            $user->assignRole('Admin');
        }

        // 4. Create Tasks in various states
        $tasks = [
            [
                'title' => 'Setup CI/CD Pipeline', 
                'status' => 'done', 
                'estimated_hours' => 5, 
                'actual_hours' => 4, 
                'is_billable' => true
            ],
            [
                'title' => 'Design Homepage Mockup', 
                'status' => 'done', 
                'estimated_hours' => 8, 
                'actual_hours' => 8, 
                'is_billable' => true
            ],
            [
                'title' => 'Integrate Payment Gateway', 
                'status' => 'in_progress', 
                'estimated_hours' => 12, 
                'actual_hours' => 0, 
                'is_billable' => true
            ],
            [
                'title' => 'Internal Team Meeting', 
                'status' => 'done', 
                'estimated_hours' => 1, 
                'actual_hours' => 1, 
                'is_billable' => false // Non-billable test
            ],
        ];

        foreach ($tasks as $t) {
            $task = Task::create([
                'project_id' => $project->id,
                'title' => $t['title'],
                'description' => 'Generated by Seeder',
                'status' => $t['status'],
                'priority' => 'high',
                'complexity' => 'medium',
                'estimated_hours' => $t['estimated_hours'],
                'actual_hours' => $t['actual_hours'],
                'is_billable' => $t['is_billable'],
                'created_by' => 1 // Admin
            ]);

            // Assign to John Doe for Pulse Metrics to catch it (Pass pivot data)
            $task->assignees()->sync([
                $dev->id
            ]);
            
            // Note: We are NOT invoicing them yet, leaving them "Unbilled" 
            // so the user can test the "Generate Invoice" flow.
        }

        $this->command->info("Scrum Demo Data Seeded: Project 'Acme Web Redesign' with 4 tasks.");
    }
}
