<!DOCTYPE html>
<html>
<head>
    <title>Audit Report #{{ $session->id }}</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; }
        .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #ddd; padding-bottom: 10px; }
        .meta { margin-bottom: 20px; }
        .meta table { width: 100%; }
        .meta td { padding: 5px; }
        .stats { background: #fdfdfd; padding: 10px; border: 1px solid #eee; margin-bottom: 20px; }
        h3 { border-bottom: 1px solid #ccc; padding-bottom: 5px; margin-top: 20px; }
        table.list { width: 100%; border-collapse: collapse; margin-top: 10px; }
        table.list th, table.list td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        table.list th { background-color: #f2f2f2; }
        .missing { color: #cc0000; }
        .found { color: #008800; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Asset Audit Certificate</h1>
        <p>Generated by HRMS Inventory Intelligence</p>
    </div>

    <div class="meta">
        <table>
            <tr>
                <td><strong>Audit ID:</strong> #{{ $session->id }}</td>
                <td><strong>Date:</strong> {{ $session->created_at->format('d M Y, H:i') }}</td>
            </tr>
            <tr>
                <td><strong>Location:</strong> {{ $session->location->name }}</td>
                <td><strong>Auditor:</strong> {{ $session->auditor->name }}</td>
            </tr>
            <tr>
                <td><strong>Status:</strong> {{ $session->status }}</td>
            </tr>
        </table>
    </div>

    <div class="stats">
        <h3>Results Summary</h3>
        <p>
            <strong>Total Expected:</strong> {{ $session->stats['total'] }}<br>
            <strong>Verified Found:</strong> {{ $session->stats['scanned'] }}<br>
            <strong>Missing:</strong> {{ $session->stats['missing'] }}<br>
            <strong>Accuracy:</strong> {{ $session->stats['accuracy'] }}%
        </p>
    </div>

    @if($session->stats['missing'] > 0)
    <h3 class="missing">Missing / Not Found Assets</h3>
    <table class="list">
        <thead>
            <tr>
                <th>Asset Tag</th>
                <th>Name</th>
                <th>Category</th>
                <th>Last Known Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($session->items->where('status', 'Missing') as $item)
            <tr>
                <td>{{ $item->asset->asset_tag ?? $item->asset->serial_number }}</td>
                <td>{{ $item->asset->name }}</td>
                <td>{{ $item->asset->category->name ?? 'N/A' }}</td>
                <td>{{ $item->asset->status }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @else
    <p class="found"><strong>Perfect Audit! No assets were missing.</strong></p>
    @endif

    <div style="margin-top: 50px; text-align: center; color: #888;">
        <p>This document certifies the physical verification of assets at the specified location.</p>
    </div>
</body>
</html>
