<!DOCTYPE html>
<html>
<head>
    <title>Engineering Operational Audit</title>
    <style>
        body { font-family: 'Helvetica', sans-serif; color: #334155; }
        .header { margin-bottom: 40px; border-bottom: 2px solid #e2e8f0; padding-bottom: 20px; }
        .header h1 { font-size: 24px; margin: 0; color: #1e293b; }
        .header p { font-size: 12px; color: #64748b; margin: 5px 0 0; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background-color: #f8fafc; text-align: left; font-size: 10px; text-transform: uppercase; letter-spacing: 0.05em; padding: 12px; border-bottom: 1px solid #e2e8f0; }
        td { padding: 12px; font-size: 11px; border-bottom: 1px solid #f1f5f9; }
        .footer { margin-top: 40px; font-size: 9px; color: #94a3b8; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Engineering Operational Audit</h1>
        <p>Project: {{ $project->name }} | Generated: {{ $generated_at }}</p>
    </div>

    <table>
        <thead>
            <tr>
                @foreach($columns as $col)
                    <th>{{ $col }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @foreach($bugs as $bug)
                <tr>
                    @foreach($columns as $col)
                        <td>
                            @php
                                $val = '';
                                switch (strtolower($col)) {
                                    case 'id': $val = $bug->id; break;
                                    case 'subject': $val = $bug->subject; break;
                                    case 'module': $val = $bug->module?->name ?? 'N/A'; break;
                                    case 'stage': $val = $bug->stage?->name; break;
                                    case 'severity': $val = $bug->severity; break;
                                    case 'priority': $val = $bug->priority; break;
                                    case 'reporter': $val = $bug->reporter?->name; break;
                                    case 'assignee': $val = $bug->assignee?->name ?? 'Unassigned'; break;
                                    case 'created': $val = $bug->created_at->format('Y-m-d'); break;
                                }
                            @endphp
                            {{ $val }}
                        </td>
                    @endforeach
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by Nexus IQ Intelligence Hub &copy; {{ date('Y') }}
    </div>
</body>
</html>
