<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Project Summary - {{ $project->code }}</title>
    <style>
        body { font-family: 'Helvetica', sans-serif; color: #1e293b; padding: 40px; }
        .header { border-bottom: 2px solid #10b981; padding-bottom: 20px; margin-bottom: 30px; }
        .title { font-size: 24px; font-weight: bold; }
        .meta { color: #64748b; font-size: 10px; text-transform: uppercase; letter-spacing: 1px; }
        .section { margin-bottom: 30px; }
        .section-title { font-size: 14px; font-weight: bold; color: #10b981; text-transform: uppercase; margin-bottom: 10px; border-bottom: 1px solid #f1f5f9; padding-bottom: 5px; }
        .grid { width: 100%; border-collapse: collapse; }
        .metric-card { background: #f8fafc; border-radius: 10px; padding: 15px; border: 1px solid #e2e8f0; width: 45%; display: inline-block; margin-right: 20px; text-align: center; }
        .metric-val { font-size: 20px; font-weight: bold; margin: 5px 0; }
        .metric-label { font-size: 9px; color: #64748b; text-transform: uppercase; }
        .doc-item { border-bottom: 1px solid #f1f5f9; padding: 10px 0; }
        .doc-name { font-size: 12px; font-weight: bold; }
        .doc-meta { font-size: 9px; color: #64748b; }
        .footer { position: fixed; bottom: 0; width: 100%; font-size: 8px; color: #94a3b8; text-align: center; border-top: 1px solid #f1f5f9; padding-top: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <div class="meta">Corporate Intelligence Summary</div>
        <div class="title">{{ $project->name }}</div>
        <div class="meta">Code: {{ $project->code }} • Client: {{ $client->name }}</div>
    </div>

    <div class="section">
        <div class="section-title">Execution Velocity</div>
        <div class="metric-card">
            <div class="metric-label">Milestone Completion</div>
            <div class="metric-val">{{ $progress }}%</div>
        </div>
        <div class="metric-card">
            <div class="metric-label">System Health Index</div>
            <div class="metric-val" style="color: {{ $health > 75 ? '#10b981' : ($health > 40 ? '#f59e0b' : '#ef4444') }}">{{ $health }}%</div>
        </div>
    </div>

    <div class="section">
        <div class="section-title">Compliance Artifacts & Sign-offs</div>
        <div style="font-size: 10px; font-weight: bold; margin-bottom: 5px;">Legally binding documents verified on {{ $exported_at }}</div>
        @foreach($signed_documents as $doc)
            <div class="doc-item">
                <div class="doc-name">{{ $doc->name }} (V{{ $doc->version_number }})</div>
                <div class="doc-meta">
                    Category: {{ ucfirst($doc->category) }} • Signed-off on: {{ $doc->signed_at->format('d M Y, H:i') }} • Verified Stakeholder UID: {{ $doc->signed_by }}
                </div>
            </div>
        @endforeach
    </div>

    <div class="section">
        <div class="section-title">Administrative Disclaimer</div>
        <p style="font-size: 8px; color: #64748b; line-height: 1.5;">
            This project summary is a point-in-time snapshot of the development trajectory and compliance status. 
            All completion metrics are current as of the export timestamp and are subject to real-time updates within the Executive Portal.
            Cryptographic verification for all digital signatures is available upon audit request.
        </p>
    </div>

    <div class="footer">
        Generated by LEAP Management System • Auditor: {{ $exported_by }} • System Ref: {{ uniqid('SR-') }}
    </div>
</body>
</html>
